### ISSUE TITLE
ESP32 example with WiFi.h not reading voltage anymore 

### ISSUE THREAD

**Issue by robbert1977** [GreenPonik/DFRobot_ESP_PH_BY_GREENPONIK#6] opened 2021-06-20 18:39 UTC
Hi there,

I've got a problem, have bought Gravity PH sensor V2 and tested it for my aquarium script.
The example is working (without calibration gives me PH 5.4.
When I test in my script it isn't reading voltage and gives PH 15.79

So I went back to example to put in my code bit by bit.
Was fairly fast found when I added WiFi.h and in seup state:
WiFi.begin(ssid, password);
The voltage is stopped reading.

Comment WiFi.begin and voltage is read again.

Please can you help me fix this?

Below the code and screenshot of Serial output see the change in voltage and reading

Kind regards robbert

`
#include "DFRobot_ESP_PH.h"
#include "EEPROM.h"
#include <WiFi.h>
const char* ssid = "MYSSID";
const char* password = "MYPASS";
DFRobot_ESP_PH ph;
#define ESPADC 4096.0   //the esp Analog Digital Convertion value
#define ESPVOLTAGE 3300 //the esp voltage supply value
#define PH_PIN 27		//the esp gpio data pin number
float voltage, phValue, temperature = 25;

void setup()
{
  Serial.begin(115200);
  EEPROM.begin(32);//needed to permit storage of calibration value in eeprom
  ph.begin();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
}

void loop()
{
  static unsigned long timepoint = millis();
  if (millis() - timepoint > 1000U) //time interval: 1s
  {
    timepoint = millis();
    //voltage = rawPinValue / esp32ADC * esp32Vin
    voltage = analogRead(PH_PIN) / ESPADC * ESPVOLTAGE; // read the voltage
    Serial.print("voltage:");
    Serial.println(voltage, 4);

    //temperature = readTemperature();  // read your temperature sensor to execute temperature compensation
    Serial.print("temperature:");
    Serial.print(temperature, 1);
    Serial.println("^C");

    phValue = ph.readPH(voltage, temperature); // convert voltage to pH with temperature compensation
    Serial.print("pH:");
    Serial.println(phValue, 4);
  }
  ph.calibration(voltage, temperature); // calibration process by Serail CMD
}

float readTemperature()
{
  //add your code here to get the temperature from your temperature sensor
}`

![image](https://user-images.githubusercontent.com/65653580/122684730-79807d80-d207-11eb-832b-a704e5f8628c.png)

**Comment by MkLHX** [comment] 2021-06-21 07:23
Hi @robbert1977 
That a really strange behavior.

Did you take attention on your SSID and password casse sensitive ?

Have you test the same code on another esp32?

**Comment by robbert1977** [comment] 2021-06-21 07:44
Hi, yes it is indeed very strange. The SSID and PASS comes straight from the working aquarium.ino (of course deleted from this post) but yes they are correct. Even if they are not correct the fact that without WiFi.h the example is reading from the data pin a voltage of 1339 and with WiFi.begin() it is 0 is something that is not related to a succesfull wifi login (or is it?) 

To be honest I'm no real programmer for a living so that's why I started from scratch with the working example.
I only added a few lines to show the problem.

I can test with another ESP32 of course but fact is that without WiFi.begin() the example code seems to work

In addition @MkLHX on this esp32 board everything else (LED, relais, temp sensors, crontab, Wifi, webserver, connection with raspberry domoticz over wifi) are working together in aquarium.ino file which I build. I will test the example and wifi tonight on another board to see if that changes the situation.

**Comment by MkLHX** [comment] 2021-06-21 09:22
yeah let me know if something change with the next esp32 board.

I never get this kind of issue, but esp32 WiFi lib is really strange and some times break code with nonsense.

**Comment by robbert1977** [comment] 2021-06-21 20:07
Ok found what is happening.
WiFi uses also an analog digital convertor and uses ADC2, as the ESP has 2 real ADC's divided over the pins.
You can only use ADC1 channel so pins 32 to 36. 
See also https://desire.giesecke.tk/index.php/2018/01/30/adc2-channel-cannot-be-used-when-wifi-is-in-use/
 
 PLease add this information to your documentation as ESP32 is for WiFi usage and this info not easy to find.
 
 Same counts for Bluetooth usage who also ADC

kind regards robbert

**Comment by MkLHX** [comment] 2021-06-21 21:13
Ok I can add it but that an esp32 shitty case.
We never encountered this behavior.
We use until 4 channel with ads1x15 without any problems.
So that not an issue from our code.

**Comment by robbert1977** [comment] 2021-06-21 21:32
No it seems a problem in usage of ADC on ESP32 as explained in the article. (and this library is specifically for the esp boards :P)
However very usefull to know as ESP32 is quite popular especially for his wifi usage.
So if your sensor doesn't work, an easy explenation why you use pin 34 in your code and not anyone below 32 (so all on ADC2 channel) would be a great help!! And now everyone can read it in here 
Thanks for your fast replying

**Comment by MkLHX** [comment] 2021-07-16 09:36
@robbert1977 i close the issue because that not a code issue and we never can reproduce this error.
This library is just a portability of DFRobot lib (the probes manufacturer).

So ESP32 conflicts or pins attribution conflicts is not an issue from c++ code and i will not list all possibile issues from theses behaviors on a code repository because that not the goal of it.

Thanks for gived us your feedback

**Closed as completed by MkLHX** 2021-07-16 09:36 UTC
